### PR TITLE
Prepped documentation repo for use in local dev + styling fix <ol>

### PR DESCRIPTION
**Pull request by verlev**
# Pull Request

## What changed?

1. Prepared the repository to be used in a local dev environment, to be able to spin webpack and preview changes in jekyll.

- Updated root .gitignore to exclude locally built dev files from webpack and the generated jekyll site folder
- Updated package.json with a local dev script "dev-all" to run wp and jekyll in parallel

2. Fixed the styling issue for ordered lists (examples on /aspireupdate)

## Why did it change?

There was no option to preview the documentation site without a GH pages build (yet).
New contributors can fork & clone the repo and be able to run both webpack and jekyll simultaneously to preview changes via livereload.

Usage:
- install jekyll and all dependencies: [https://jekyllrb.com/docs/](https://jekyllrb.com/docs/)
- `npm install --dev`
- `bundle install`
- `npm run dev-all` (run livereload wp + jekyll, preview URL: http://127.0.0.1:4001/)
- ready? `npm run prod` (to build prod files + update manifest.yml)

## Did you fix any specific issues?

Local dev preview ready
#22 

## CERTIFICATION

By opening this pull request, I do agree to abide by the [Code of Conduct](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CONTRIBUTING.md) in effect on the date and time of my contribution as proven by the revision information in GitHub.

### CODE REVIEW

**Comment by verlev** [comment]
Please take your time!
I could not test the GH Pages build flow, only my local Jekyll build. So this is actually untested IRL... (you might need time to revert when something would be wrong.. I expect GH to be able to re-build the pages with the newly generated JS/CSS)

**Review by asirota — APPROVED** [review]

**Comment by AmnestyAM** [comment]
PS I don't have Ruby Jekyl etc running on my local so cant properly test this stuff, I am happy to take an informed guess and do PRs to roll back if they break on release. @asirota are you happy with me taking that approach in the future?

**Comment by asirota** [comment]
Sure thing. The only stuff that needs changing is the docs sub folder and the structure within. 

We don't have local full installs and I don't think they are required tbh to test the system unless we are making design changes to the layout.

**Comment by verlev** [comment]
fyi
@asirota we do have a full local install (I have) :)

All content work can be done in /docs
Except for the menu: _data/menu_v2.yml

All styling/HTML template work can be forwarded to me, or I could help anyone set up the local dev.

**Comment by AmnestyAM** [comment]
That works for me :-) I will get set up with this running locally within a week or so

**Comment by verlev** [comment]
@AmnestyAM When you do, please let me know if the 'Local setup' and 'Run' scenario's in the PR comment is correct and complete, I have more notes, do not think they're needed/wanted for all (though some may be).

**Comment by asirota** [comment]
Somehow I feel you both are exactly the right people to help this. @verlev let's hold a workshop to setup an install together.

**Pull request merged**
